spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/QuizApp
    username: JK_Credentials
    password: Database_2003
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

server:
  error:
    include-message: always